//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UID { get; set; }
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your User ID.")]
        [DisplayName("User Name")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your Password")]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string Pswd { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Address { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
